const symbols=['ㄅ','ㄆ','ㄇ','ㄈ','ㄉ','ㄊ','ㄋ','ㄌ','ㄍ','ㄎ','ㄏ','ㄐ','ㄑ','ㄒ','ㄓ','ㄔ','ㄕ','ㄖ','ㄗ','ㄘ','ㄙ','ㄧ','ㄨ','ㄩ','ㄚ','ㄛ','ㄜ','ㄝ','ㄞ','ㄟ','ㄠ','ㄡ','ㄢ','ㄣ','ㄤ','ㄥ','ㄦ'];
const tones=['ˉ','ˊ','ˇ','ˋ','˙'];
const dict={'ㄅ':['不','把','被','比','白','爸','班','幫'],'ㄅㄚ':['八','巴','吧','拔','把','爸'],'ㄅㄚˋ':['爸','霸','罷'],'ㄨ':['我','無','五','物','午'],'ㄨㄛ':['我','握','窩'],'ㄨㄛˇ':['我'],'ㄋ':['你','那','年','能','哪'],'ㄋㄧ':['你','尼','泥','妮'],'ㄋㄧˇ':['你','擬'],'ㄏ':['好','和','喝','很','會','還'],'ㄏㄠ':['好','號','豪'],'ㄏㄠˇ':['好'],'ㄏㄜ':['喝','和','河','合'],'ㄏㄜ':['喝','和','河','合'],'ㄕ':['是','想','上','水','說','什'],'ㄒ':['想','小','先','喜','謝'],'ㄒㄧㄤ':['想','香','鄉','相'],'ㄒㄧㄤˇ':['想','響'],'ㄏㄜˉ':['喝'],'ㄕㄨㄟˇ':['水'],'ㄋㄧㄡˊ':['牛'],'ㄋㄞˇ':['奶']};
let composing='', sentence=''; const $=id=>document.getElementById(id);
function say(t){ if(!t)return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(t);u.lang='zh-TW';u.rate=.85;speechSynthesis.speak(u)}
function phoneticSay(x){const names={'ˉ':'一聲','ˊ':'二聲','ˇ':'三聲','ˋ':'四聲','˙':'輕聲'};say(names[x]||x)}
function candidates(){let exact=dict[composing]||[]; if(!exact.length&&composing){const all=[];for(const [k,v] of Object.entries(dict))if(k.startsWith(composing))all.push(...v);exact=[...new Set(all)]} return exact.slice(0,12)}
function render(){ $('sentence').textContent=sentence||'請用下方注音開始輸入…'; $('compose').textContent=composing||'　'; $('cands').innerHTML=''; candidates().forEach(w=>{let b=document.createElement('button');b.className='cand';b.textContent=w;b.onclick=()=>{sentence+=w; composing=''; say(w);render()};$('cands').appendChild(b)})}
function makeKeys(){[...symbols,...tones].forEach(x=>{let b=document.createElement('button');b.className='key '+(tones.includes(x)?'tone':'zhuyin');if(tones.includes(x)){b.textContent=x}else{const g=document.createElement('span');g.className='glyph';g.textContent=x;b.appendChild(g)}b.onclick=()=>{composing+=x;phoneticSay(x);render()};$('keys').appendChild(b)});[['⌫','back'],['空格','space']].forEach(([t,a])=>{let b=document.createElement('button');b.className='key action';b.textContent=t;b.onclick=()=>{if(a==='back'){if(composing)composing=composing.slice(0,-1);else sentence=sentence.slice(0,-1)}else sentence+=' ';render()};$('keys').appendChild(b)})}
let favs=JSON.parse(localStorage.getItem('zhuyinFavs')||'["我要","不要","幫忙","上廁所","休息"]');
function saveFav(i){if(!sentence){alert('請先在上方輸入要儲存的句子。');return}if(confirm(`要將「${sentence}」儲存到這一格嗎？`)){favs[i]=sentence;localStorage.setItem('zhuyinFavs',JSON.stringify(favs));renderFavs()}}
function renderFavs(){$('favorites').innerHTML='';favs.forEach((x,i)=>{let b=document.createElement('button');b.className='fav';b.textContent=x||'＋常用語';let timer;b.onpointerdown=()=>timer=setTimeout(()=>saveFav(i),700);b.onpointerup=()=>clearTimeout(timer);b.onpointercancel=()=>clearTimeout(timer);b.onclick=()=>{sentence+=x;say(x);render()};$('favorites').appendChild(b)})}
$('speak').onclick=()=>say(sentence);$('clear').onclick=()=>{sentence='';composing='';render()};makeKeys();renderFavs();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
